name: Checkov Security Scan with CheckOV

on:
  push:
    branches:
      - '*'  # Trigger for any push to any branch
 
  pull_request:
    branches:
      - '*'  # Trigger for any PR to any branch

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (OpenJDK 11)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan
        run: |
          checkov -d . --output junitxml --download-external-modules > checkov_output.xml

      - name: Generate Allure Report
        run: |
          curl -sSL https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.zip -o allure.zip
          unzip allure.zip
          ./allure-2.13.9/bin/allure generate checkov_output.xml --clean -o allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
