name: Terraform Scan with TerraScan

on:
  push:
    branches:
      - '*'  # Trigger for any push to any branch
 
  pull_request:
    branches:
      - '*'  # # Trigger on pull request to the main branch 

jobs:
  terrascan:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Install TerraScan v1.19.9
        run: |
          curl -sSL https://github.com/tenable/terrascan/releases/download/v1.19.9/terrascan_1.19.9_Linux_x86_64.tar.gz -o terrascan.tar.gz
          tar -xvzf terrascan.tar.gz
          sudo mv terrascan /usr/local/bin/

      - name: Run TerraScan scan
        run: |
          terrascan scan -t aws -o human -d . > terrascan_report.human

      - name: Upload TerraScan Report
        uses: actions/upload-artifact@v4
        with:
          name: terrascan-report
          path: terrascan_report.human
