name: Trivy Repository Scan
 
on:
  push:
    branches:
      - '*'  # Trigger for any push to any branch
 
  pull_request:
    branches:
      - '*'  # Trigger for any PR to any branch
 
jobs:
  trivy-scan:
    name: Scan Repository with Trivy
    runs-on: ubuntu-latest
 
    steps:
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin v0.58.2
        echo "$HOME/bin" >> $GITHUB_PATH
        wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O $HOME/bin/html.tpl
 
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Run Trivy Scan for Vulnerabilities
      id: trivy-scan
      run: |
        echo "Running Trivy scan on repository files..."
        trivy fs --timeout 20m --scanners misconfig,secret --format template --template "@$HOME/bin/html.tpl" -o trivy-report.html --severity CRITICAL,HIGH --no-progress .        
    - name: Upload Trivy HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.html
 
    - name: Check CRITICAL vulnerabilities and exit if found.
      id: check-critical-vul
      run: |
        # Check for CRITICAL vulnerabilities in the HTML report
        if grep -ri "<td class=\"severity\">CRITICAL</td>" trivy-report.html; then
          echo "CRITICAL vulnerabilities found!"
          exit 1  # Fail the job if CRITICAL vulnerabilities are found
        fi
